### ISSUE TITLE
Ask for confirmation when deleting

### ISSUE THREAD

**Issue by apbetioli** [apbetioli/estimate3d#31]
Add a simple confirmation dialog when deleting records. Create a custom dialog, not the browser default.

**Comment by AryanKuAg** [comment]
could u assign this to me? @apbetioli

**Comment by apbetioli** [comment]
@AryanKuAg assigned to you. Let me know if you need more details.

**Comment by AryanKuAg** [comment]
so, there r three tabs (prints, printers, filaments) which can contains the item that can be deleted, I just have to add the dialog box there, right? and also there is this delete button
![image](https://github.com/apbetioli/estimate3d/assets/61811630/02e16b2f-c77f-4b91-9064-3761f9944ae4)
Do I have to add the dialog box here too? @apbetioli

**Comment by AryanKuAg** [comment]
Hi @apbetioli , I've added this confirmation pop up in this PR: https://github.com/apbetioli/estimate3d/pull/33, pls suggest me any changes that I should make or I missed, I'm ready for any kind of contribution
![image](https://github.com/apbetioli/estimate3d/assets/61811630/95d945fd-94d0-4a80-a998-d2e1e1e43e1a)
