### ISSUE TITLE
Refactor svg icons

### ISSUE THREAD

**Issue by apbetioli** [apbetioli/estimate3d#39]
Create an `Icons.tsx` 'component' and export each svg used in the project to be used as components, instead of embedding the SVG itself.

**Comment by apbetioli** [comment]
Assigned to you @AnukratiMehta, thanks!

**Comment by AnukratiMehta** [comment]
> Assigned to you @AnukratiMehta, thanks!

Thanks, @apbetioli. I missed this before. Have made the changes and created a pull request now. Thanks!
